language: node_js
sudo: false
node_js:
- '8'
- '10'
- '11'
- '12'
script:
- yarn test
before_install:
  - export PATH="$PATH:`yarn global bin`"
  - yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: npmjs@heise.de
  api_key:
    secure: "MkTk70SuzTERh/kHryCupQdGN06UetnXQSgkDXJkSHWYqCl4th21nkHYT5kZLyj0g4FZ8foc8zDOwG/71GY6GlYZBbyh6hbQsw/qzAXae6vhdN0mkz0VjMLuAlZr8wVAnMp8StxJPOvEiKgRHzrnfjeOL8IMpwTNieYN1vcMEKLy6TaZQFVPQsWUhzHDY8H/XzcHYJICp7nZMNmZiE/CeMqJDHJa5NqwL6bT6GjaSvAd0DyILhzCv+Fi1w4suittcivUz9EQV1Bfoiw7A7Gm4bCnMt5EqvyAVKSCo94+nmqKpqayDkCNXGpqmCqgT3P6orrUcxEXaWBikh+tSe5DVrshsL80lJRP1uqx1zgxxQCwjizXzAJNsMBqi+r2oV9qvN902mDgy+4YANgm2QRPwzaKWe42PPGln2oLnNsj7vjTk6BcQ30TtxfrZoyNr2Ooa5ykEQGgPI9DXylZVbrdU7eneSYmDsX1v7oVZiKxaxT+gSqVZHKMJoyeanNVk7R1bumJ/yVMMCBVBtosGTFR7OuZx3Z7r+17VUgFEOVGTomTKCGq5Rbtd7gbQNe5DV9LjBmaN4nAlvZqAG/Rk1vB0tnQxcOxFn9pBJc7oNsXjF11Ve0yNjC5nd5n2AL+5VlGd2z877b/6ejRP2vVwZ65RwyCk60ZPGhvTSEtHn1z36E="
  on:
    tags: true
    repo: heiseonline/request-promise-native-record
    node_js: '8'
env:
  global:
    secure: ZJ2A+YqqLfcRmOYG6+36ZapATBi2sVRjvHr+o6rVHfFIz6ltQCam2HvPmaHjIEu5A/ha1kktMtFFzWXiz2MjaGGe2754Xcv91832Uq9F5bxnHimDM6EeCS6EMvWyqwuaRKTSFoSJA4S8QvCWkTEVr/LkUTdxwDAKa/VXtxi4/E2D9cz28tKMEUFh4EVRewB8XOmg38VjGuoy9QtuHF/iXAif4TsPu9wXCRvLtdW00dyRAsKj2myHPbuvZTW1w5hBi4u7B3TcwxmORxBrDHmppU8IioVpIHhHnR81RdSJkqjq6ehch3B4HpMeFt0XyJTedHjtFMN7Kn+n1y8tLcscbdazsS8GgzFpq6tWWfkGhI9hJ0hucwaXXm8HZudlaBIQaizEMScwYiq8kHq7P1dyKl24WFpTf9kJivU+j110s+oxpiRXRVaDcbyJ51c+RnqSzc3KMDtJX8zk/bN+J83wXdkOIBsHgehKQgb7PhMGAiiVtaxZt/h9bp0iMScXwd/MUlGA5XUizU46EE3BkU9meD110RJFUAHfCc64YIfTJmCoa6wpOIRQ0ZoTsWlWAMayHL/k0ZFQXDRY/rGuwk8NNFndniq+J0fsVhGVQhOYk4UXxwskutSJf2LUYa3lOVF/NHni7msYbuQFFYV06pB2NekrZu3Xj2Zsjc6JEX+bLec=
